// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceInterfaceDemo.proto

package org.yutil.grpc.proto;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoService.User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
