// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceInterfaceDemo.proto

package org.yutil.grpc.proto;

public interface UserListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoService.UserList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.DemoService.User users = 1;</code>
   */
  boolean hasUsers();
  /**
   * <code>.DemoService.User users = 1;</code>
   */
  org.yutil.grpc.proto.User getUsers();
  /**
   * <code>.DemoService.User users = 1;</code>
   */
  org.yutil.grpc.proto.UserOrBuilder getUsersOrBuilder();
}
