// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceInterfaceDemo.proto

package org.mw.grpc.proto;

public interface UserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DemoService.UserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint64 id = 1;</code>
   */
  long getId();
}
