// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GrpcServiceInterfaceDemo.proto

package org.yutil.grpc.proto;

/**
 * Protobuf type {@code DemoService.UserList}
 */
public  final class UserList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DemoService.UserList)
    UserListOrBuilder {
  // Use UserList.newBuilder() to construct.
  private UserList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserList() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private UserList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            org.yutil.grpc.proto.User.Builder subBuilder = null;
            if (users_ != null) {
              subBuilder = users_.toBuilder();
            }
            users_ = input.readMessage(org.yutil.grpc.proto.User.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(users_);
              users_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.yutil.grpc.proto.DemoeService.internal_static_DemoService_UserList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.yutil.grpc.proto.DemoeService.internal_static_DemoService_UserList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.yutil.grpc.proto.UserList.class, org.yutil.grpc.proto.UserList.Builder.class);
  }

  public static final int USERS_FIELD_NUMBER = 1;
  private org.yutil.grpc.proto.User users_;
  /**
   * <code>.DemoService.User users = 1;</code>
   */
  public boolean hasUsers() {
    return users_ != null;
  }
  /**
   * <code>.DemoService.User users = 1;</code>
   */
  public org.yutil.grpc.proto.User getUsers() {
    return users_ == null ? org.yutil.grpc.proto.User.getDefaultInstance() : users_;
  }
  /**
   * <code>.DemoService.User users = 1;</code>
   */
  public org.yutil.grpc.proto.UserOrBuilder getUsersOrBuilder() {
    return getUsers();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (users_ != null) {
      output.writeMessage(1, getUsers());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (users_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUsers());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.yutil.grpc.proto.UserList)) {
      return super.equals(obj);
    }
    org.yutil.grpc.proto.UserList other = (org.yutil.grpc.proto.UserList) obj;

    boolean result = true;
    result = result && (hasUsers() == other.hasUsers());
    if (hasUsers()) {
      result = result && getUsers()
          .equals(other.getUsers());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUsers()) {
      hash = (37 * hash) + USERS_FIELD_NUMBER;
      hash = (53 * hash) + getUsers().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.yutil.grpc.proto.UserList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.yutil.grpc.proto.UserList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.yutil.grpc.proto.UserList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.yutil.grpc.proto.UserList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.yutil.grpc.proto.UserList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DemoService.UserList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DemoService.UserList)
      org.yutil.grpc.proto.UserListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.yutil.grpc.proto.DemoeService.internal_static_DemoService_UserList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.yutil.grpc.proto.DemoeService.internal_static_DemoService_UserList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.yutil.grpc.proto.UserList.class, org.yutil.grpc.proto.UserList.Builder.class);
    }

    // Construct using org.yutil.grpc.proto.UserList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (usersBuilder_ == null) {
        users_ = null;
      } else {
        users_ = null;
        usersBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.yutil.grpc.proto.DemoeService.internal_static_DemoService_UserList_descriptor;
    }

    public org.yutil.grpc.proto.UserList getDefaultInstanceForType() {
      return org.yutil.grpc.proto.UserList.getDefaultInstance();
    }

    public org.yutil.grpc.proto.UserList build() {
      org.yutil.grpc.proto.UserList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.yutil.grpc.proto.UserList buildPartial() {
      org.yutil.grpc.proto.UserList result = new org.yutil.grpc.proto.UserList(this);
      if (usersBuilder_ == null) {
        result.users_ = users_;
      } else {
        result.users_ = usersBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.yutil.grpc.proto.UserList) {
        return mergeFrom((org.yutil.grpc.proto.UserList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.yutil.grpc.proto.UserList other) {
      if (other == org.yutil.grpc.proto.UserList.getDefaultInstance()) return this;
      if (other.hasUsers()) {
        mergeUsers(other.getUsers());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.yutil.grpc.proto.UserList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.yutil.grpc.proto.UserList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private org.yutil.grpc.proto.User users_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.yutil.grpc.proto.User, org.yutil.grpc.proto.User.Builder, org.yutil.grpc.proto.UserOrBuilder> usersBuilder_;
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public boolean hasUsers() {
      return usersBuilder_ != null || users_ != null;
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public org.yutil.grpc.proto.User getUsers() {
      if (usersBuilder_ == null) {
        return users_ == null ? org.yutil.grpc.proto.User.getDefaultInstance() : users_;
      } else {
        return usersBuilder_.getMessage();
      }
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public Builder setUsers(org.yutil.grpc.proto.User value) {
      if (usersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        users_ = value;
        onChanged();
      } else {
        usersBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public Builder setUsers(
        org.yutil.grpc.proto.User.Builder builderForValue) {
      if (usersBuilder_ == null) {
        users_ = builderForValue.build();
        onChanged();
      } else {
        usersBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public Builder mergeUsers(org.yutil.grpc.proto.User value) {
      if (usersBuilder_ == null) {
        if (users_ != null) {
          users_ =
            org.yutil.grpc.proto.User.newBuilder(users_).mergeFrom(value).buildPartial();
        } else {
          users_ = value;
        }
        onChanged();
      } else {
        usersBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public Builder clearUsers() {
      if (usersBuilder_ == null) {
        users_ = null;
        onChanged();
      } else {
        users_ = null;
        usersBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public org.yutil.grpc.proto.User.Builder getUsersBuilder() {
      
      onChanged();
      return getUsersFieldBuilder().getBuilder();
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    public org.yutil.grpc.proto.UserOrBuilder getUsersOrBuilder() {
      if (usersBuilder_ != null) {
        return usersBuilder_.getMessageOrBuilder();
      } else {
        return users_ == null ?
            org.yutil.grpc.proto.User.getDefaultInstance() : users_;
      }
    }
    /**
     * <code>.DemoService.User users = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.yutil.grpc.proto.User, org.yutil.grpc.proto.User.Builder, org.yutil.grpc.proto.UserOrBuilder> 
        getUsersFieldBuilder() {
      if (usersBuilder_ == null) {
        usersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.yutil.grpc.proto.User, org.yutil.grpc.proto.User.Builder, org.yutil.grpc.proto.UserOrBuilder>(
                getUsers(),
                getParentForChildren(),
                isClean());
        users_ = null;
      }
      return usersBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:DemoService.UserList)
  }

  // @@protoc_insertion_point(class_scope:DemoService.UserList)
  private static final org.yutil.grpc.proto.UserList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.yutil.grpc.proto.UserList();
  }

  public static org.yutil.grpc.proto.UserList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserList>
      PARSER = new com.google.protobuf.AbstractParser<UserList>() {
    public UserList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserList> getParserForType() {
    return PARSER;
  }

  public org.yutil.grpc.proto.UserList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

