// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoMessageHeader.proto

package org.yutil.kafka.common;

public final class ProtoMessageHeader {
  private ProtoMessageHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kafka_util.MessageHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 key = 1;</code>
     */
    long getKey();

    /**
     * <code>int32 type = 2;</code>
     */
    int getType();

    /**
     * <code>int32 partitionId = 3;</code>
     */
    int getPartitionId();

    /**
     * <code>int64 timestamp = 4;</code>
     */
    long getTimestamp();

    /**
     * <code>int64 producerId = 5;</code>
     */
    long getProducerId();

    /**
     * <code>int64 offset = 6;</code>
     */
    long getOffset();

    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry>
        getAttributeEntryList();
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    ProtoMessageHeader.MessageHeader.AttributeEntry getAttributeEntry(int index);
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    int getAttributeEntryCount();
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    java.util.List<? extends ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder>
        getAttributeEntryOrBuilderList();
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder getAttributeEntryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code kafka_util.MessageHeader}
   */
  public  static final class MessageHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kafka_util.MessageHeader)
      MessageHeaderOrBuilder {
    // Use MessageHeader.newBuilder() to construct.
    private MessageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageHeader() {
      key_ = 0L;
      type_ = 0;
      partitionId_ = 0;
      timestamp_ = 0L;
      producerId_ = 0L;
      offset_ = 0L;
      attributeEntry_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MessageHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              key_ = input.readInt64();
              break;
            }
            case 16: {

              type_ = input.readInt32();
              break;
            }
            case 24: {

              partitionId_ = input.readInt32();
              break;
            }
            case 32: {

              timestamp_ = input.readInt64();
              break;
            }
            case 40: {

              producerId_ = input.readInt64();
              break;
            }
            case 48: {

              offset_ = input.readInt64();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                attributeEntry_ = new java.util.ArrayList<ProtoMessageHeader.MessageHeader.AttributeEntry>();
                mutable_bitField0_ |= 0x00000040;
              }
              attributeEntry_.add(
                  input.readMessage(ProtoMessageHeader.MessageHeader.AttributeEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          attributeEntry_ = java.util.Collections.unmodifiableList(attributeEntry_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoMessageHeader.MessageHeader.class, ProtoMessageHeader.MessageHeader.Builder.class);
    }

    public interface AttributeEntryOrBuilder extends
        // @@protoc_insertion_point(interface_extends:kafka_util.MessageHeader.AttributeEntry)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */
      int getAttributeMapCount();
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */
      boolean containsAttributeMap(
          java.lang.String key);
      /**
       * Use {@link #getAttributeMapMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.String, java.lang.String>
      getAttributeMap();
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */
      java.util.Map<java.lang.String, java.lang.String>
      getAttributeMapMap();
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      java.lang.String getAttributeMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue);
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      java.lang.String getAttributeMapOrThrow(
          java.lang.String key);
    }
    /**
     * Protobuf type {@code kafka_util.MessageHeader.AttributeEntry}
     */
    public  static final class AttributeEntry extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:kafka_util.MessageHeader.AttributeEntry)
        AttributeEntryOrBuilder {
      // Use AttributeEntry.newBuilder() to construct.
      private AttributeEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private AttributeEntry() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private AttributeEntry(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                  attributeMap_ = com.google.protobuf.MapField.newMapField(
                      AttributeMapDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000001;
                }
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                attributeMap__ = input.readMessage(
                    AttributeMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                attributeMap_.getMutableMap().put(
                    attributeMap__.getKey(), attributeMap__.getValue());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetAttributeMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMessageHeader.MessageHeader.AttributeEntry.class, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder.class);
      }

      public static final int ATTRIBUTEMAP_FIELD_NUMBER = 1;
      private static final class AttributeMapDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            java.lang.String, java.lang.String> defaultEntry =
                com.google.protobuf.MapEntry
                .<java.lang.String, java.lang.String>newDefaultInstance(
                    ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_descriptor,
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "");
      }
      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> attributeMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAttributeMap() {
        if (attributeMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttributeMapDefaultEntryHolder.defaultEntry);
        }
        return attributeMap_;
      }

      public int getAttributeMapCount() {
        return internalGetAttributeMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      public boolean containsAttributeMap(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttributeMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttributeMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAttributeMap() {
        return getAttributeMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getAttributeMapMap() {
        return internalGetAttributeMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      public java.lang.String getAttributeMapOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributeMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attributeMap = 1;</code>
       */

      public java.lang.String getAttributeMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAttributeMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetAttributeMap(),
            AttributeMapDefaultEntryHolder.defaultEntry,
            1);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
             : internalGetAttributeMap().getMap().entrySet()) {
          com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
          attributeMap__ = AttributeMapDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(1, attributeMap__);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoMessageHeader.MessageHeader.AttributeEntry)) {
          return super.equals(obj);
        }
        ProtoMessageHeader.MessageHeader.AttributeEntry other = (ProtoMessageHeader.MessageHeader.AttributeEntry) obj;

        boolean result = true;
        result = result && internalGetAttributeMap().equals(
            other.internalGetAttributeMap());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (!internalGetAttributeMap().getMap().isEmpty()) {
          hash = (37 * hash) + ATTRIBUTEMAP_FIELD_NUMBER;
          hash = (53 * hash) + internalGetAttributeMap().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoMessageHeader.MessageHeader.AttributeEntry parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoMessageHeader.MessageHeader.AttributeEntry prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code kafka_util.MessageHeader.AttributeEntry}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:kafka_util.MessageHeader.AttributeEntry)
          ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 1:
              return internalGetAttributeMap();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 1:
              return internalGetMutableAttributeMap();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoMessageHeader.MessageHeader.AttributeEntry.class, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder.class);
        }

        // Construct using ProtoMessageHeader.MessageHeader.AttributeEntry.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          internalGetMutableAttributeMap().clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor;
        }

        public ProtoMessageHeader.MessageHeader.AttributeEntry getDefaultInstanceForType() {
          return ProtoMessageHeader.MessageHeader.AttributeEntry.getDefaultInstance();
        }

        public ProtoMessageHeader.MessageHeader.AttributeEntry build() {
          ProtoMessageHeader.MessageHeader.AttributeEntry result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ProtoMessageHeader.MessageHeader.AttributeEntry buildPartial() {
          ProtoMessageHeader.MessageHeader.AttributeEntry result = new ProtoMessageHeader.MessageHeader.AttributeEntry(this);
          int from_bitField0_ = bitField0_;
          result.attributeMap_ = internalGetAttributeMap();
          result.attributeMap_.makeImmutable();
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoMessageHeader.MessageHeader.AttributeEntry) {
            return mergeFrom((ProtoMessageHeader.MessageHeader.AttributeEntry)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoMessageHeader.MessageHeader.AttributeEntry other) {
          if (other == ProtoMessageHeader.MessageHeader.AttributeEntry.getDefaultInstance()) return this;
          internalGetMutableAttributeMap().mergeFrom(
              other.internalGetAttributeMap());
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoMessageHeader.MessageHeader.AttributeEntry parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoMessageHeader.MessageHeader.AttributeEntry) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.MapField<
            java.lang.String, java.lang.String> attributeMap_;
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetAttributeMap() {
          if (attributeMap_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                AttributeMapDefaultEntryHolder.defaultEntry);
          }
          return attributeMap_;
        }
        private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableAttributeMap() {
          onChanged();;
          if (attributeMap_ == null) {
            attributeMap_ = com.google.protobuf.MapField.newMapField(
                AttributeMapDefaultEntryHolder.defaultEntry);
          }
          if (!attributeMap_.isMutable()) {
            attributeMap_ = attributeMap_.copy();
          }
          return attributeMap_;
        }

        public int getAttributeMapCount() {
          return internalGetAttributeMap().getMap().size();
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public boolean containsAttributeMap(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          return internalGetAttributeMap().getMap().containsKey(key);
        }
        /**
         * Use {@link #getAttributeMapMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String> getAttributeMap() {
          return getAttributeMapMap();
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public java.util.Map<java.lang.String, java.lang.String> getAttributeMapMap() {
          return internalGetAttributeMap().getMap();
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public java.lang.String getAttributeMapOrDefault(
            java.lang.String key,
            java.lang.String defaultValue) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.String> map =
              internalGetAttributeMap().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public java.lang.String getAttributeMapOrThrow(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.String> map =
              internalGetAttributeMap().getMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }

        public Builder clearAttributeMap() {
          internalGetMutableAttributeMap().getMutableMap()
              .clear();
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public Builder removeAttributeMap(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          internalGetMutableAttributeMap().getMutableMap()
              .remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.String>
        getMutableAttributeMap() {
          return internalGetMutableAttributeMap().getMutableMap();
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */
        public Builder putAttributeMap(
            java.lang.String key,
            java.lang.String value) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          if (value == null) { throw new java.lang.NullPointerException(); }
          internalGetMutableAttributeMap().getMutableMap()
              .put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, string&gt; attributeMap = 1;</code>
         */

        public Builder putAllAttributeMap(
            java.util.Map<java.lang.String, java.lang.String> values) {
          internalGetMutableAttributeMap().getMutableMap()
              .putAll(values);
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:kafka_util.MessageHeader.AttributeEntry)
      }

      // @@protoc_insertion_point(class_scope:kafka_util.MessageHeader.AttributeEntry)
      private static final ProtoMessageHeader.MessageHeader.AttributeEntry DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoMessageHeader.MessageHeader.AttributeEntry();
      }

      public static ProtoMessageHeader.MessageHeader.AttributeEntry getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<AttributeEntry>
          PARSER = new com.google.protobuf.AbstractParser<AttributeEntry>() {
        public AttributeEntry parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new AttributeEntry(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<AttributeEntry> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<AttributeEntry> getParserForType() {
        return PARSER;
      }

      public ProtoMessageHeader.MessageHeader.AttributeEntry getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int KEY_FIELD_NUMBER = 1;
    private long key_;
    /**
     * <code>int64 key = 1;</code>
     */
    public long getKey() {
      return key_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>int32 type = 2;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int PARTITIONID_FIELD_NUMBER = 3;
    private int partitionId_;
    /**
     * <code>int32 partitionId = 3;</code>
     */
    public int getPartitionId() {
      return partitionId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 4;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int PRODUCERID_FIELD_NUMBER = 5;
    private long producerId_;
    /**
     * <code>int64 producerId = 5;</code>
     */
    public long getProducerId() {
      return producerId_;
    }

    public static final int OFFSET_FIELD_NUMBER = 6;
    private long offset_;
    /**
     * <code>int64 offset = 6;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int ATTRIBUTEENTRY_FIELD_NUMBER = 7;
    private java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry> attributeEntry_;
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    public java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry> getAttributeEntryList() {
      return attributeEntry_;
    }
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    public java.util.List<? extends ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder>
        getAttributeEntryOrBuilderList() {
      return attributeEntry_;
    }
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    public int getAttributeEntryCount() {
      return attributeEntry_.size();
    }
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    public ProtoMessageHeader.MessageHeader.AttributeEntry getAttributeEntry(int index) {
      return attributeEntry_.get(index);
    }
    /**
     * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
     */
    public ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder getAttributeEntryOrBuilder(
        int index) {
      return attributeEntry_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (key_ != 0L) {
        output.writeInt64(1, key_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (partitionId_ != 0) {
        output.writeInt32(3, partitionId_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(4, timestamp_);
      }
      if (producerId_ != 0L) {
        output.writeInt64(5, producerId_);
      }
      if (offset_ != 0L) {
        output.writeInt64(6, offset_);
      }
      for (int i = 0; i < attributeEntry_.size(); i++) {
        output.writeMessage(7, attributeEntry_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (key_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, key_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (partitionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, partitionId_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (producerId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, producerId_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, offset_);
      }
      for (int i = 0; i < attributeEntry_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, attributeEntry_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoMessageHeader.MessageHeader)) {
        return super.equals(obj);
      }
      ProtoMessageHeader.MessageHeader other = (ProtoMessageHeader.MessageHeader) obj;

      boolean result = true;
      result = result && (getKey()
          == other.getKey());
      result = result && (getType()
          == other.getType());
      result = result && (getPartitionId()
          == other.getPartitionId());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && (getProducerId()
          == other.getProducerId());
      result = result && (getOffset()
          == other.getOffset());
      result = result && getAttributeEntryList()
          .equals(other.getAttributeEntryList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getKey());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + PARTITIONID_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionId();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + PRODUCERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProducerId());
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      if (getAttributeEntryCount() > 0) {
        hash = (37 * hash) + ATTRIBUTEENTRY_FIELD_NUMBER;
        hash = (53 * hash) + getAttributeEntryList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMessageHeader.MessageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMessageHeader.MessageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoMessageHeader.MessageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoMessageHeader.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMessageHeader.MessageHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kafka_util.MessageHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kafka_util.MessageHeader)
        ProtoMessageHeader.MessageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoMessageHeader.MessageHeader.class, ProtoMessageHeader.MessageHeader.Builder.class);
      }

      // Construct using ProtoMessageHeader.MessageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAttributeEntryFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        key_ = 0L;

        type_ = 0;

        partitionId_ = 0;

        timestamp_ = 0L;

        producerId_ = 0L;

        offset_ = 0L;

        if (attributeEntryBuilder_ == null) {
          attributeEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          attributeEntryBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoMessageHeader.internal_static_kafka_util_MessageHeader_descriptor;
      }

      public ProtoMessageHeader.MessageHeader getDefaultInstanceForType() {
        return ProtoMessageHeader.MessageHeader.getDefaultInstance();
      }

      public ProtoMessageHeader.MessageHeader build() {
        ProtoMessageHeader.MessageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoMessageHeader.MessageHeader buildPartial() {
        ProtoMessageHeader.MessageHeader result = new ProtoMessageHeader.MessageHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.key_ = key_;
        result.type_ = type_;
        result.partitionId_ = partitionId_;
        result.timestamp_ = timestamp_;
        result.producerId_ = producerId_;
        result.offset_ = offset_;
        if (attributeEntryBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            attributeEntry_ = java.util.Collections.unmodifiableList(attributeEntry_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.attributeEntry_ = attributeEntry_;
        } else {
          result.attributeEntry_ = attributeEntryBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMessageHeader.MessageHeader) {
          return mergeFrom((ProtoMessageHeader.MessageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMessageHeader.MessageHeader other) {
        if (other == ProtoMessageHeader.MessageHeader.getDefaultInstance()) return this;
        if (other.getKey() != 0L) {
          setKey(other.getKey());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getPartitionId() != 0) {
          setPartitionId(other.getPartitionId());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (other.getProducerId() != 0L) {
          setProducerId(other.getProducerId());
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (attributeEntryBuilder_ == null) {
          if (!other.attributeEntry_.isEmpty()) {
            if (attributeEntry_.isEmpty()) {
              attributeEntry_ = other.attributeEntry_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureAttributeEntryIsMutable();
              attributeEntry_.addAll(other.attributeEntry_);
            }
            onChanged();
          }
        } else {
          if (!other.attributeEntry_.isEmpty()) {
            if (attributeEntryBuilder_.isEmpty()) {
              attributeEntryBuilder_.dispose();
              attributeEntryBuilder_ = null;
              attributeEntry_ = other.attributeEntry_;
              bitField0_ = (bitField0_ & ~0x00000040);
              attributeEntryBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAttributeEntryFieldBuilder() : null;
            } else {
              attributeEntryBuilder_.addAllMessages(other.attributeEntry_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoMessageHeader.MessageHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoMessageHeader.MessageHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long key_ ;
      /**
       * <code>int64 key = 1;</code>
       */
      public long getKey() {
        return key_;
      }
      /**
       * <code>int64 key = 1;</code>
       */
      public Builder setKey(long value) {
        
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 2;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int partitionId_ ;
      /**
       * <code>int32 partitionId = 3;</code>
       */
      public int getPartitionId() {
        return partitionId_;
      }
      /**
       * <code>int32 partitionId = 3;</code>
       */
      public Builder setPartitionId(int value) {
        
        partitionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 partitionId = 3;</code>
       */
      public Builder clearPartitionId() {
        
        partitionId_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timestamp = 4;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private long producerId_ ;
      /**
       * <code>int64 producerId = 5;</code>
       */
      public long getProducerId() {
        return producerId_;
      }
      /**
       * <code>int64 producerId = 5;</code>
       */
      public Builder setProducerId(long value) {
        
        producerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 producerId = 5;</code>
       */
      public Builder clearProducerId() {
        
        producerId_ = 0L;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>int64 offset = 6;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>int64 offset = 6;</code>
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 offset = 6;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry> attributeEntry_ =
        java.util.Collections.emptyList();
      private void ensureAttributeEntryIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          attributeEntry_ = new java.util.ArrayList<ProtoMessageHeader.MessageHeader.AttributeEntry>(attributeEntry_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoMessageHeader.MessageHeader.AttributeEntry, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder, ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder> attributeEntryBuilder_;

      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry> getAttributeEntryList() {
        if (attributeEntryBuilder_ == null) {
          return java.util.Collections.unmodifiableList(attributeEntry_);
        } else {
          return attributeEntryBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public int getAttributeEntryCount() {
        if (attributeEntryBuilder_ == null) {
          return attributeEntry_.size();
        } else {
          return attributeEntryBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public ProtoMessageHeader.MessageHeader.AttributeEntry getAttributeEntry(int index) {
        if (attributeEntryBuilder_ == null) {
          return attributeEntry_.get(index);
        } else {
          return attributeEntryBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder setAttributeEntry(
          int index, ProtoMessageHeader.MessageHeader.AttributeEntry value) {
        if (attributeEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeEntryIsMutable();
          attributeEntry_.set(index, value);
          onChanged();
        } else {
          attributeEntryBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder setAttributeEntry(
          int index, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder builderForValue) {
        if (attributeEntryBuilder_ == null) {
          ensureAttributeEntryIsMutable();
          attributeEntry_.set(index, builderForValue.build());
          onChanged();
        } else {
          attributeEntryBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder addAttributeEntry(ProtoMessageHeader.MessageHeader.AttributeEntry value) {
        if (attributeEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeEntryIsMutable();
          attributeEntry_.add(value);
          onChanged();
        } else {
          attributeEntryBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder addAttributeEntry(
          int index, ProtoMessageHeader.MessageHeader.AttributeEntry value) {
        if (attributeEntryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAttributeEntryIsMutable();
          attributeEntry_.add(index, value);
          onChanged();
        } else {
          attributeEntryBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder addAttributeEntry(
          ProtoMessageHeader.MessageHeader.AttributeEntry.Builder builderForValue) {
        if (attributeEntryBuilder_ == null) {
          ensureAttributeEntryIsMutable();
          attributeEntry_.add(builderForValue.build());
          onChanged();
        } else {
          attributeEntryBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder addAttributeEntry(
          int index, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder builderForValue) {
        if (attributeEntryBuilder_ == null) {
          ensureAttributeEntryIsMutable();
          attributeEntry_.add(index, builderForValue.build());
          onChanged();
        } else {
          attributeEntryBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder addAllAttributeEntry(
          java.lang.Iterable<? extends ProtoMessageHeader.MessageHeader.AttributeEntry> values) {
        if (attributeEntryBuilder_ == null) {
          ensureAttributeEntryIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, attributeEntry_);
          onChanged();
        } else {
          attributeEntryBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder clearAttributeEntry() {
        if (attributeEntryBuilder_ == null) {
          attributeEntry_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          attributeEntryBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public Builder removeAttributeEntry(int index) {
        if (attributeEntryBuilder_ == null) {
          ensureAttributeEntryIsMutable();
          attributeEntry_.remove(index);
          onChanged();
        } else {
          attributeEntryBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public ProtoMessageHeader.MessageHeader.AttributeEntry.Builder getAttributeEntryBuilder(
          int index) {
        return getAttributeEntryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder getAttributeEntryOrBuilder(
          int index) {
        if (attributeEntryBuilder_ == null) {
          return attributeEntry_.get(index);  } else {
          return attributeEntryBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public java.util.List<? extends ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder>
           getAttributeEntryOrBuilderList() {
        if (attributeEntryBuilder_ != null) {
          return attributeEntryBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(attributeEntry_);
        }
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public ProtoMessageHeader.MessageHeader.AttributeEntry.Builder addAttributeEntryBuilder() {
        return getAttributeEntryFieldBuilder().addBuilder(
            ProtoMessageHeader.MessageHeader.AttributeEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public ProtoMessageHeader.MessageHeader.AttributeEntry.Builder addAttributeEntryBuilder(
          int index) {
        return getAttributeEntryFieldBuilder().addBuilder(
            index, ProtoMessageHeader.MessageHeader.AttributeEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .kafka_util.MessageHeader.AttributeEntry attributeEntry = 7;</code>
       */
      public java.util.List<ProtoMessageHeader.MessageHeader.AttributeEntry.Builder>
           getAttributeEntryBuilderList() {
        return getAttributeEntryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoMessageHeader.MessageHeader.AttributeEntry, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder, ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder>
          getAttributeEntryFieldBuilder() {
        if (attributeEntryBuilder_ == null) {
          attributeEntryBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoMessageHeader.MessageHeader.AttributeEntry, ProtoMessageHeader.MessageHeader.AttributeEntry.Builder, ProtoMessageHeader.MessageHeader.AttributeEntryOrBuilder>(
                  attributeEntry_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          attributeEntry_ = null;
        }
        return attributeEntryBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:kafka_util.MessageHeader)
    }

    // @@protoc_insertion_point(class_scope:kafka_util.MessageHeader)
    private static final ProtoMessageHeader.MessageHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMessageHeader.MessageHeader();
    }

    public static ProtoMessageHeader.MessageHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageHeader>
        PARSER = new com.google.protobuf.AbstractParser<MessageHeader>() {
      public MessageHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MessageHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageHeader> getParserForType() {
      return PARSER;
    }

    public ProtoMessageHeader.MessageHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kafka_util_MessageHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kafka_util_MessageHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kafka_util_MessageHeader_AttributeEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ProtoMessageHeader.proto\022\nkafka_util\"\322" +
      "\002\n\rMessageHeader\022\013\n\003key\030\001 \001(\003\022\014\n\004type\030\002 " +
      "\001(\005\022\023\n\013partitionId\030\003 \001(\005\022\021\n\ttimestamp\030\004 " +
      "\001(\003\022\022\n\nproducerId\030\005 \001(\003\022\016\n\006offset\030\006 \001(\003\022" +
      "@\n\016attributeEntry\030\007 \003(\0132(.kafka_util.Mes" +
      "sageHeader.AttributeEntry\032\227\001\n\016AttributeE" +
      "ntry\022P\n\014attributeMap\030\001 \003(\0132:.kafka_util." +
      "MessageHeader.AttributeEntry.AttributeMa" +
      "pEntry\0323\n\021AttributeMapEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\r\n\005value\030\002 \001(\t:\0028\001B&\n\020org.kafka.commonB",
      "\022ProtoMessageHeaderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kafka_util_MessageHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kafka_util_MessageHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kafka_util_MessageHeader_descriptor,
        new java.lang.String[] { "Key", "Type", "PartitionId", "Timestamp", "ProducerId", "Offset", "AttributeEntry", });
    internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor =
      internal_static_kafka_util_MessageHeader_descriptor.getNestedTypes().get(0);
    internal_static_kafka_util_MessageHeader_AttributeEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor,
        new java.lang.String[] { "AttributeMap", });
    internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_descriptor =
      internal_static_kafka_util_MessageHeader_AttributeEntry_descriptor.getNestedTypes().get(0);
    internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kafka_util_MessageHeader_AttributeEntry_AttributeMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
